### ISSUE TITLE
Option for persistent notification and action button 

### ISSUE THREAD

**Issue by rakesh-oasys** [Basel-525k/geofence_foreground_service#5]
I am creating a app where user location is tracking while the app is in background. The notification also coming while the app is in background but my requirment is unless the user is not clicked on dismiss/Action buttions the notification will stick to the notification bar.

Thanks,
Rakesh

**Comment by byshy** [comment]
To make sure I understand the issue correctly, you want the persistent notification that appears on android when the app is closed to be removed? if so then unfortunately this doesn't conform the Android guidelines as every app that runs in the background should give the user an indication that it's running, the notification is not dismissible as long as the app is running.

**Comment by byshy** [comment]
Oh okay, I got your point

The notifications that are displayed from the library are only visible when the debug mode is enabled, disabling it will prevent notifications from appearing

You can use other notification packages to help with that, you can trigger them from within the handler method, by doing so you'll achieve your goal of displaying custom notifications based on geofence triggers (keeping in mind that you diable the debug mode)
