### ISSUE TITLE
Enable controlling Android setNotificationResponsiveness

### ISSUE THREAD

**Issue by orkun1675** [Basel-525k/geofence_foreground_service#7]
Thanks for the great plugin, I'm integrating it now and look forward to trying it out!

Per the Android docs: https://developers.google.com/android/reference/com/google/android/gms/location/Geofence.Builder#public-geofence.builder-setnotificationresponsiveness-int-notificationresponsivenessms

> Setting a big responsiveness value, for example 5 minutes, can save power significantly.

Since our use case would be okay with a 5 minute delay it would be great to be able to set this value via the plugin APIs.

**Comment by Basel-525k** [comment]
Thanks for reaching out! Pull requests are always welcome.

If you need any help with the process or have questions about the code, just let me know. I’m here to help!
